#!/bin/bash -x

set -e

# Download the files
wget http://downloads.sourceforge.net/project/postfixadmin/postfixadmin/postfixadmin-2.92/postfixadmin-2.92.tar.gz
tar -xf postfixadmin-2.92.tar.gz
rm -f postfixadmin-2.92.tar.gz

# Copy to proper directory
mkdir -p /var/www/${PACKER_DOMAIN}
mv postfixadmin-2.92 /var/www/${PACKER_DOMAIN}/postfixadmin
chown -R www-data:www-data /var/www/${PACKER_DOMAIN}/postfixadmin

# Configure nginx
# TODO: change port to 5000 once proxied
# MARK: ipv6
cat > /etc/nginx/sites-available/root << EOF
server {
    listen 80;

    # Make site accessible from http://localhost/
    server_name localhost;

    root /var/www/${PACKER_DOMAIN};
    index index.html index.php;

    location / {
        # First attempt to serve request as file, then
        # as directory, then fall back to displaying a 404.
        try_files \$uri \$uri/ =404;
        # Uncomment to enable naxsi on this location
        # include /etc/nginx/naxsi.rules
    }

    location ~ \\.php$ {
        try_files \$uri \$uri/ =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        # NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini

        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
    }

    access_log /var/log/nginx/${PACKER_DOMAIN}.access.log;
    error_log /var/log/nginx/${PACKER_DOMAIN}.error.log;
}
EOF
rm -f /etc/nginx/sites-enabled/default
ln -s ../sites-available/root /etc/nginx/sites-enabled/root
service nginx reload

# Configure postfixadmin
configfile=/var/www/${PACKER_DOMAIN}/postfixadmin/config.inc.php
sed -i "s/^\$CONF\['configured'\].*$/\$CONF['configured'] = true;/" $configfile
# MARK: https
sed -i "s/^\$CONF\['postfix_admin_url'\].*$/\$CONF['postfix_admin_url'] = 'http:\/\/${PACKER_DOMAIN}\/postfixadmin';/" $configfile
sed -i "s/^\$CONF\['database_user'\].*$/\$CONF['database_user'] = 'mail';/" $configfile
sed -i "s/^\$CONF\['database_password'\].*$/\$CONF['database_password'] = '${MYSQL_MAIL_ADMIN_PASSWORD}';/" $configfile
sed -i "s/^\$CONF\['database_name'\].*$/\$CONF['database_name'] = 'mail';/" $configfile
sed -i "s/^\$CONF\['admin_email'\].*$/\$CONF['admin_email'] = 'postmaster@${PACKER_DOMAIN}';/" $configfile
sed -i "s/^\$CONF\['encrypt'\].*$/\$CONF['encrypt'] = 'dovecot:SHA256-CRYPT:';/" $configfile
sed -i "s/'abuse' => .*$/'abuse' => 'admin@${PACKER_DOMAIN}',/" $configfile
sed -i "s/'hostmaster' => .*$/'hostmaster' => 'admin@${PACKER_DOMAIN}',/" $configfile
sed -i "s/'postmaster' => .*$/'postmaster' => 'admin@${PACKER_DOMAIN}',/" $configfile
sed -i "s/'webmaster' => .*$/'webmaster' => 'admin@${PACKER_DOMAIN}'/" $configfile
# MARK: https
sed -i "s/^\$CONF\['user_footer_link'\].*$/\$CONF['user_footer_link'] = 'http:\/\/${PACKER_DOMAIN}\/';/" $configfile
sed -i "s/^\$CONF\['footer_text'\].*$/\$CONF['footer_text'] = 'Return to ${PACKER_DOMAIN}';/" $configfile
# MARK: https
sed -i "s/^\$CONF\['footer_link'\].*$/\$CONF['footer_link'] = 'http:\/\/${PACKER_DOMAIN}\/';/" $configfile
