#!/bin/bash -x

set -e

echo "dovecot-core dovecot-core/create-ssl-cert boolean false" | debconf-set-selections
echo "postfix postfix/mailname string ${PACKER_HOSTNAME}.${PACKER_DOMAIN}" | debconf-set-selections
echo "postfix postfix/main_mailer_type select Internet Site" | debconf-set-selections
apt-get -y install postfix postfix-mysql postfix-doc dovecot-common dovecot-imapd dovecot-pop3d libsasl2-2 libsasl2-modules libsasl2-modules-sql sasl2-bin libpam-mysql openssl telnet mailutils
