#!/bin/bash -x

set -e

# Set selections for dovecot and postfix
echo "dovecot-core dovecot-core/create-ssl-cert boolean false" | debconf-set-selections
echo "postfix postfix/mailname string ${PACKER_HOSTNAME}.${PACKER_DOMAIN}" | debconf-set-selections
echo "postfix postfix/main_mailer_type select Internet Site" | debconf-set-selections

# Install base packages
apt-get -y install python python-minimal python2.7 python2.7-minimal libpython-stdlib libpython2.7-stdlib libpython2.7-minimal dovecot-core dovecot-pop3d dovecot-imapd postfix mutt libtokyocabinet9 libassuan0 libwrap0 ssl-cert bsd-mailx procmail tcpd libgpgme11 openssl telnet mailutils

# Install necessary php modules
apt-get -y install php5-imap
# php5-imap doesn't set its symlinks (because it lacks priority?), doing it manually.
# Same for phhp5-mcrypt, see php install-script.
ln -s ../../mods-available/imap.ini /etc/php5/fpm/conf.d/imap.ini
ln -s ../../mods-available/imap.ini /etc/php5/cli/conf.d/imap.ini

# Install antispam packages
apt-get -y install postgrey amavis clamav clamav-daemon spamassassin pyzor razor arj cabextract lzop nomarch p7zip-full ripole rpm2cpio tnef unzip unrar-free zip zoo
