#!/bin/bash -x

set -e

apt-get -y install postfix-mysql dovecot-mysql

mysql -u root -p${MYSQL_ROOT_PASSWORD} << EOF

CREATE DATABASE mail;
GRANT ALL ON mail.* TO 'mail'@'localhost' IDENTIFIED BY '${MYSQL_MAIL_ADMIN_PASSWORD}';

EOF
