#!/bin/bash -x

set -e

# Configure dovecot
dovecotsqlconfig=/etc/dovecot/dovecot-sql.conf.ext
sed -i "s/^#driver =.*$/driver = mysql/" $dovecotsqlconfig
sed -i "s/^#connect =.*$/connect = host=localhost dbname=mail user=mail password=${MYSQL_MAIL_ADMIN_PASSWORD}/" $dovecotsqlconfig
sed -i "s/^#default_pass_scheme =.*$/default_pass_scheme = SHA256-CRYPT/" $dovecotsqlconfig

echo "password_query = \\
  SELECT username as user, password, '/var/vmail/%d/%n' as userdb_home, \\
  'maildir:/var/vmail/%d/%n' as userdb_mail, 150 as userdb_uid, 8 as userdb_gid \\
  FROM mailbox WHERE username = '%u' AND active = '1'" >> $dovecotsqlconfig
echo "user_query = \\
  SELECT '/var/vmail/%d/%n' as home, 'maildir:/var/vmail/%d/%n' as mail, \\
  150 AS uid, 8 AS gid, concat('dirsize:storage=', quota) AS quota \\
  FROM mailbox WHERE username = '%u' AND active = '1'" >> $dovecotsqlconfig

dovecotauthconfig=/etc/dovecot/conf.d/10-auth.conf
sed -i "s/^#disable_plaintext_auth =.*$/disable_plaintext_auth = yes/" $dovecotauthconfig
sed -i "s/^auth_mechanisms = .*$/auth_mechanisms = plain login/" $dovecotauthconfig
sed -i "s/^\!include auth-system.conf.ext$/#\!include auth-system.conf.ext/" $dovecotauthconfig
sed -i "s/^#\!include auth-sql.conf.ext$/\!include auth-sql.conf.ext/" $dovecotauthconfig

dovecotmailconfig=/etc/dovecot/conf.d/10-mail.conf
sed -i "s/^mail_location =.*$/mail_location = maildir:\/var\/vmail\/%d\/%n/" $dovecotmailconfig
sed -i "s/^#mail_uid =.*$/mail_uid = vmail/" $dovecotmailconfig
sed -i "s/^#mail_gid =.*$/mail_gid = mail/" $dovecotmailconfig
sed -i "s/^#first_valid_uid =.*$/first_valid_uid = 150/" $dovecotmailconfig
sed -i "s/^#last_valid_uid =.*$/last_valid_uid = 150/" $dovecotmailconfig
sed -i "s/^#first_valid_gid =.*$/first_valid_gid = 8/" $dovecotmailconfig
sed -i "s/^#last_valid_gid =.*$/last_valid_gid = 8/" $dovecotmailconfig

dovecotsslconfig=/etc/dovecot/conf.d/10-ssl.conf
sed -i "s/^#ssl =.*$/ssl = yes/" $dovecotsslconfig
sed -i "s/^ssl_cert =.*$/ssl_cert = <\/etc\/ssl\/certs\/ssl-cert-snakeoil.pem/" $dovecotsslconfig
sed -i "s/^ssl_key =.*$/ssl_key = <\/etc\/ssl\/private\/ssl-cert-snakeoil.key/" $dovecotsslconfig
sed -i "s/^#ssl_protocols =.*$/ssl_protocols = \!SSLv2 \!SSLv3/" $dovecotsslconfig
sed -i "s/^#ssl_cipher_list =.*$/ssl_cipher_list =  ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:\!aNULL:\!MD5:\!DSS/" $dovecotsslconfig

dovecotmasterconfig=/etc/dovecot/conf.d/10-master.conf
sed -i "90,92s/^    #mode =.*$/    mode = 0666/" $dovecotmasterconfig
sed -i "90,92s/^    #user =.*$/    user = vmail/" $dovecotmasterconfig
sed -i "90,92s/^    #group =.*$/    group = mail/" $dovecotmasterconfig
sed -i "96,98s/^  #unix_listener/  unix_listener/" $dovecotmasterconfig
sed -i "96,98s/^  #}$/  }/" $dovecotmasterconfig
sed -i "96,98s/^  #  mode =.*$/    mode = 0666\n    user = postfix\n    group = postfix/" $dovecotmasterconfig

chown -R vmail:dovecot /etc/dovecot
chmod -R o-rwx /etc/dovecot
