#!/bin/bash -x

set -e

echo "mysql-server-5.5 mysql-server/root_password password ${MYSQL_ROOT_PASSWORD}" | debconf-set-selections
echo "mysql-server-5.5 mysql-server/root_password_again password ${MYSQL_ROOT_PASSWORD}" | debconf-set-selections
apt-get -y install mysql-client mysql-server
