#!/bin/bash -x

set -e

mysql -u root -p${MYSQL_ROOT_PASSWORD} << EOF

CREATE DATABASE mail;
USE mail;

GRANT SELECT, INSERT, UPDATE, DELETE ON mail.* TO 'mail_admin'@'localhost' IDENTIFIED BY '${MYSQL_MAIL_ADMIN_PASSWORD}';
GRANT SELECT, INSERT, UPDATE, DELETE ON mail.* TO 'mail_admin'@'localhost.localdomain' IDENTIFIED BY '${MYSQL_MAIL_ADMIN_PASSWORD}';
FLUSH PRIVILEGES;

CREATE TABLE domains (domain varchar(150) NOT NULL, PRIMARY KEY (domain) );
CREATE TABLE forwardings (source varchar(150) NOT NULL, destination TEXT NOT NULL, PRIMARY KEY (source) );
CREATE TABLE users (email varchar(150) NOT NULL, password varchar(150) NOT NULL, PRIMARY KEY (email) );
CREATE TABLE transport ( domain varchar(150) NOT NULL default '', transport varchar(150) NOT NULL default '', UNIQUE KEY domain (domain) );
EOF
